"use client";

import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";

type IconName = "arrow" | "cake" | "cart" | "check" | "clock" | "close" | "heart" | "leaf" | "lock" | "pin" | "search" | "send" | "sparkle" | "star" | "truck" | "upload" | "user";
type AdminTab = "overview" | "cakes" | "orders" | "delivery" | "customers" | "analytics" | "inventory" | "reviews" | "staff";
type AdminCake = { id: number; backendId?: string; name: string; category: string; price: number; image: string; tag: string; soldOut: boolean; stock: number; margin: number; orders: number };
type AdminOrder = { id: string; backendId?: string; customer: string; cake: string; amount: number; status: string; time: string; driver: string; delivery: string };
type InventoryItem = { name: string; unit: string; stock: number; reorderAt: number; cost: string };
type Review = { id: number; customer: string; cake: string; rating: number; quote: string; status: "Pending" | "Approved" };
type AdminCatalogueCake = { id: string; name: string; status: string; basePrice: number; categories: Array<{ id: string; name: string }>; variants: Array<{ isActive: boolean; stock: number }> };
type AdminCataloguePayload = { cakes: AdminCatalogueCake[]; categories: Array<{ id: string; name: string }> };
type AdminOrderRecord = { id: string; orderNumber: string; customer: string; status: string; total: number; placedAt: string; courier: string | null; fulfillmentType: string; items: Array<{ cakeName: string; variantName: string | null; quantity: number }> };

const imageBase = "https://images.unsplash.com/";
const initialCakes: AdminCake[] = [
  { id: 1, name: "Strawberry Cloud", category: "Birthday", price: 4200, image: `${imageBase}photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80`, tag: "Bestseller", soldOut: false, stock: 18, margin: 46, orders: 86 },
  { id: 2, name: "Dark Cocoa Dream", category: "Chocolate", price: 4600, image: `${imageBase}photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80`, tag: "Rich & fudgy", soldOut: false, stock: 14, margin: 51, orders: 64 },
  { id: 3, name: "Lemon Garden", category: "Anniversary", price: 4400, image: `${imageBase}photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=600&q=80`, tag: "New season", soldOut: false, stock: 9, margin: 42, orders: 31 },
  { id: 4, name: "Pink Petal Party", category: "Baby shower", price: 5000, image: `${imageBase}photo-1557925923-cd4648e211a0?auto=format&fit=crop&w=600&q=80`, tag: "Made to order", soldOut: false, stock: 12, margin: 48, orders: 42 },
  { id: 5, name: "Golden Hour", category: "Wedding", price: 7200, image: `${imageBase}photo-1535254973040-6b8c2c0a6d3c?auto=format&fit=crop&w=600&q=80`, tag: "Elegant", soldOut: false, stock: 6, margin: 39, orders: 28 },
  { id: 6, name: "Coconut Fig", category: "Vegan / eggless", price: 4800, image: `${imageBase}photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=600&q=80`, tag: "Plant based", soldOut: true, stock: 0, margin: 36, orders: 19 },
];

const initialOrders: AdminOrder[] = [
  { id: "BB-2841", customer: "Nia Wanjiku", cake: "Strawberry Cloud · 1 kg", amount: 4550, status: "Baking", time: "Today · 9:42am", driver: "Unassigned", delivery: "Kilimani" },
  { id: "BB-2840", customer: "Maya & Tom", cake: "Golden Hour · 2 kg", amount: 12960, status: "Decorating", time: "Today · 8:18am", driver: "David K.", delivery: "Karen" },
  { id: "BB-2839", customer: "Brian Karanja", cake: "Dark Cocoa Dream · 1 kg", amount: 4950, status: "Pending", time: "Yesterday · 4:31pm", driver: "Unassigned", delivery: "Westlands" },
  { id: "BB-2838", customer: "Asha M.", cake: "The Tiny Bloom · 6 pack", amount: 2950, status: "Out for delivery", time: "Yesterday · 11:06am", driver: "Faith N.", delivery: "Lavington" },
  { id: "BB-2837", customer: "Joel Otieno", cake: "Coconut Fig · 1 kg", amount: 5150, status: "Delivered", time: "Yesterday · 9:12am", driver: "David K.", delivery: "Runda" },
];

const initialInventory: InventoryItem[] = [
  { name: "Wheat flour", unit: "kg", stock: 42, reorderAt: 18, cost: "KSh 160 / kg" },
  { name: "Free-range eggs", unit: "trays", stock: 7, reorderAt: 10, cost: "KSh 430 / tray" },
  { name: "Whipping cream", unit: "litres", stock: 12, reorderAt: 8, cost: "KSh 540 / litre" },
  { name: "Dark chocolate", unit: "kg", stock: 4, reorderAt: 6, cost: "KSh 1,250 / kg" },
  { name: "Fresh strawberries", unit: "kg", stock: 9, reorderAt: 5, cost: "KSh 700 / kg" },
];

const initialReviews: Review[] = [
  { id: 1, customer: "Linet M.", cake: "Strawberry Cloud", rating: 5, quote: "The prettiest cake and so fresh. Everyone asked for another slice.", status: "Pending" },
  { id: 2, customer: "Sam K.", cake: "Dark Cocoa Dream", rating: 5, quote: "Rich, fudgy and exactly on time. A new family favorite.", status: "Approved" },
  { id: 3, customer: "Ruth A.", cake: "Coconut Fig", rating: 4, quote: "Loved that it was eggless without feeling like a compromise.", status: "Pending" },
];

const navigation: { id: AdminTab; label: string; icon: IconName }[] = [
  { id: "overview", label: "Overview", icon: "sparkle" }, { id: "cakes", label: "Cake management", icon: "cake" }, { id: "orders", label: "Orders", icon: "cart" }, { id: "delivery", label: "Delivery", icon: "truck" }, { id: "customers", label: "Customers", icon: "user" }, { id: "analytics", label: "Analytics", icon: "star" }, { id: "inventory", label: "Inventory", icon: "leaf" }, { id: "reviews", label: "Reviews", icon: "heart" }, { id: "staff", label: "Staff & roles", icon: "user" },
];

const permissions: Record<string, string[]> = {
  "Super admin": ["Everything", "Revenue & analytics", "Staff permissions"],
  Baker: ["Cake recipes & stock", "Baking queue", "Order status: baking"],
  "Delivery staff": ["Assigned deliveries", "Delivery status", "Customer address"],
  "Customer support": ["Orders & customer notes", "Reviews moderation", "WhatsApp support"],
};

function Icon({ name, size = 18 }: { name: IconName; size?: number }) {
  const props = { width: size, height: size, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 1.8, strokeLinecap: "round" as const, strokeLinejoin: "round" as const, "aria-hidden": true };
  const paths: Record<IconName, React.ReactNode> = {
    arrow: <><path d="M5 12h13" /><path d="m13 6 6 6-6 6" /></>, cake: <><path d="M4 13h16v5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z" /><path d="M4 13c2 2 3 2 4 0 1 2 3 2 4 0 1 2 3 2 4 0 1 2 2 2 4 0" /><path d="M8 9a2 2 0 1 0 4 0c0-1.5-2-2-2-4-2 2-2 3-2 4Z" /></>, cart: <><path d="M3 4h2l2 11h10l3-8H6" /><path d="M9 19.5a1 1 0 1 0 0 .01" /><path d="M17 19.5a1 1 0 1 0 0 .01" /></>, check: <path d="m5 12 4 4L19 6" />, clock: <><circle cx="12" cy="12" r="8.5" /><path d="M12 7v5l3 2" /></>, close: <><path d="m6 6 12 12" /><path d="M18 6 6 18" /></>, heart: <path d="M20.8 8.7c0 5.5-8.8 10.2-8.8 10.2S3.2 14.2 3.2 8.7A4.7 4.7 0 0 1 12 6.2a4.7 4.7 0 0 1 8.8 2.5Z" />, leaf: <><path d="M20 4C11 4 5 8 5 14c0 3 2 5 5 5 6 0 10-6 10-15Z" /><path d="M4 20c3-4 6-7 11-10" /></>, lock: <><rect x="5" y="10" width="14" height="10" rx="2" /><path d="M8 10V7a4 4 0 0 1 8 0v3" /></>, pin: <><path d="M19 10c0 5-7 10-7 10S5 15 5 10a7 7 0 1 1 14 0Z" /><circle cx="12" cy="10" r="2.3" /></>, search: <><circle cx="10.8" cy="10.8" r="6.3" /><path d="m16 16 4.5 4.5" /></>, send: <><path d="m21 3-7 18-3.5-7.5L3 10Z" /><path d="M21 3 10.5 13.5" /></>, sparkle: <><path d="m12 3 1.2 4.8L18 9l-4.8 1.2L12 15l-1.2-4.8L6 9l4.8-1.2Z" /><path d="m19 15 .6 2.4L22 18l-2.4.6L19 21l-.6-2.4L16 18l2.4-.6Z" /></>, star: <path fill="currentColor" stroke="none" d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-2.9-5.6 2.9 1.1-6.2L3 9.6l6.2-.9Z" />, truck: <><path d="M3 6h11v10H3z" /><path d="M14 10h4l3 3v3h-7z" /><circle cx="7" cy="18" r="1.7" /><circle cx="18" cy="18" r="1.7" /></>, upload: <><path d="M12 16V4" /><path d="m7 9 5-5 5 5" /><path d="M5 20h14" /></>, user: <><circle cx="12" cy="8" r="3.5" /><path d="M5 20c.7-3.4 3-5 7-5s6.3 1.6 7 5" /></>,
  };
  return <svg {...props}>{paths[name]}</svg>;
}

function formatPrice(amount: number) { return `KSh ${amount.toLocaleString("en-KE")}`; }

export default function AdminPage() {
  const [tab, setTab] = useState<AdminTab>("overview");
  const [cakes, setCakes] = useState<AdminCake[]>(initialCakes);
  const [orders, setOrders] = useState<AdminOrder[]>(initialOrders);
  const [stock, setStock] = useState<InventoryItem[]>(initialInventory);
  const [reviews, setReviews] = useState<Review[]>(initialReviews);
  const [query, setQuery] = useState("");
  const [orderFilter, setOrderFilter] = useState("All orders");
  const [role, setRole] = useState("Super admin");
  const [editor, setEditor] = useState<AdminCake | null>(null);
  const [newCake, setNewCake] = useState({ name: "", category: "Birthday", price: "4200", soldOut: false, photo: "" });
  const [toast, setToast] = useState("");
  const [catalogueCategories, setCatalogueCategories] = useState<Array<{ id: string; name: string }>>([]);

  useEffect(() => {
    let isMounted = true;
    async function loadCatalogue() {
      try {
        const response = await fetch("/api/admin/cakes", { credentials: "same-origin" });
        if (!response.ok) return;
        const payload = await response.json() as { data?: AdminCataloguePayload };
        if (!payload.data || !isMounted) return;
        setCatalogueCategories(payload.data.categories);
        setCakes(payload.data.cakes.map((cake, index) => {
          const fallback = initialCakes.find((item) => item.name === cake.name) ?? initialCakes[0];
          const stock = cake.variants.reduce((total, variant) => total + variant.stock, 0);
          return { ...fallback, id: index + 1, backendId: cake.id, name: cake.name, category: cake.categories[0]?.name ?? "Uncategorised", price: cake.basePrice, tag: cake.status, soldOut: !cake.variants.some((variant) => variant.isActive), stock };
        }));
      } catch {
        // Keep the visual prototype data visible if the protected API is unavailable.
      }
    }
    void loadCatalogue();
    return () => { isMounted = false; };
  }, []);

  useEffect(() => {
    const statusLabel: Record<string, string> = { PENDING_PAYMENT: "Pending", PAID: "Paid", CONFIRMED: "Accepted", PREPARING: "Baking", READY_FOR_DISPATCH: "Decorating", OUT_FOR_DELIVERY: "Out for delivery", DELIVERED: "Delivered", COMPLETED: "Delivered", CANCELLED: "Rejected", FAILED: "Rejected" };
    let isMounted = true;
    async function loadOrders() {
      try {
        const response = await fetch("/api/admin/orders", { credentials: "same-origin" });
        if (!response.ok) return;
        const payload = await response.json() as { data?: AdminOrderRecord[] };
        if (!payload.data || !isMounted) return;
        setOrders(payload.data.map((order) => ({ id: order.orderNumber, backendId: order.id, customer: order.customer, cake: order.items.map((item) => `${item.quantity} × ${item.cakeName}${item.variantName ? ` · ${item.variantName}` : ""}`).join(", "), amount: order.total, status: statusLabel[order.status] ?? order.status, time: new Date(order.placedAt).toLocaleString("en-KE"), driver: order.courier ?? "Unassigned", delivery: order.fulfillmentType === "DELIVERY" ? "Delivery" : "Pickup" })));
      } catch {
        // Keep the prototype order data visible while the service is unavailable.
      }
    }
    void loadOrders();
    return () => { isMounted = false; };
  }, []);

  const filteredCakes = cakes.filter((cake) => `${cake.name} ${cake.category}`.toLowerCase().includes(query.toLowerCase()));
  const filteredOrders = orders.filter((order) => orderFilter === "All orders" || order.status === orderFilter);
  const pendingOrders = orders.filter((order) => order.status === "Pending").length;
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2600); };
  const updateOrder = async (id: string, field: "status" | "driver", value: string) => {
    const order = orders.find((item) => item.id === id);
    const statuses: Record<string, string> = { Pending: "PENDING_PAYMENT", Paid: "PAID", Accepted: "CONFIRMED", Baking: "PREPARING", Decorating: "READY_FOR_DISPATCH", "Out for delivery": "OUT_FOR_DELIVERY", Delivered: "DELIVERED", Rejected: "CANCELLED" };
    if (field === "status" && order?.backendId && statuses[value]) {
      const response = await fetch(`/api/admin/orders/${order.backendId}`, { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: statuses[value] }) }).catch(() => null);
      if (!response?.ok) { notify("That status change is not allowed yet"); return; }
    }
    setOrders((items) => items.map((item) => item.id === id ? { ...item, [field]: value } : item));
    notify(`${id} updated`);
  };

  async function saveCake(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const price = Number(newCake.price);
    if (!newCake.name.trim() || !price) { notify("Add a name and valid price"); return; }
    if (editor) {
      const category = catalogueCategories.find((item) => item.name === newCake.category);
      if (editor.backendId) {
        if (!category) { notify("This category is not available in the catalogue yet"); return; }
        const response = await fetch(`/api/admin/cakes/${editor.backendId}`, { method: "PATCH", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: newCake.name, basePrice: price, categoryId: category.id, isAvailable: !newCake.soldOut }) });
        if (!response.ok) { notify("Could not save these cake changes. Please try again."); return; }
      }
      setCakes((items) => items.map((cake) => cake.id === editor.id ? { ...cake, name: newCake.name, category: newCake.category, price, soldOut: newCake.soldOut, stock: newCake.soldOut ? 0 : Math.max(cake.stock, 12), tag: newCake.soldOut ? "Sold out" : cake.tag } : cake));
    }
    else {
      const category = catalogueCategories.find((item) => item.name === newCake.category);
      if (!category) { notify("This category is not available in the catalogue yet"); return; }
      const slug = newCake.name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
      const response = await fetch("/api/admin/cakes", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: newCake.name, slug, basePrice: price, categoryIds: [category.id], variants: [{ name: "1 kg", sku: `CUSTOM-${Date.now()}`, price }] }) });
      if (!response.ok) { notify("Could not add this cake. Check the menu details and try again."); return; }
      const payload = await response.json() as { data?: { id: string } };
      setCakes((items) => [{ ...initialCakes[0], id: Math.max(...items.map((cake) => cake.id)) + 1, backendId: payload.data?.id, name: newCake.name, category: newCake.category, price, soldOut: newCake.soldOut, stock: newCake.soldOut ? 0 : 12, tag: newCake.soldOut ? "Sold out" : "New" }, ...items]);
    }
    setEditor(null); notify(editor ? "Cake updated" : "Cake added to menu");
  }

  const openEditor = (cake?: AdminCake) => { setEditor(cake ?? null); setNewCake({ name: cake?.name ?? "", category: cake?.category ?? "Birthday", price: String(cake?.price ?? 4200), soldOut: cake?.soldOut ?? false, photo: "" }); };

  return <main className="admin-page"><section className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span className="brand-mark"><Icon name="cake" size={22} /></span><span><strong>BITE <i>&</i> BLOOM</strong><small>STUDIO ADMIN</small></span></div><nav className="admin-nav" aria-label="Admin navigation">{navigation.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}><Icon name={item.icon} size={16} /><span>{item.label}</span>{item.id === "orders" && pendingOrders > 0 && <b>{pendingOrders}</b>}</button>)}</nav><div className="admin-sidebar-bottom"><label><span>Viewing as</span><select value={role} onChange={(event) => setRole(event.target.value)}>{Object.keys(permissions).map((item) => <option key={item}>{item}</option>)}</select></label><a href="/" className="admin-back-link"><Icon name="arrow" size={15} /> Back to storefront</a></div></aside><div className="admin-main"><header className="admin-header"><div><p className="eyebrow">Tuesday · 06 August 2026</p><h2>Good morning, <em>studio.</em></h2></div><div className="admin-header-actions"><span className="admin-role-badge"><span /> {role}</span><button onClick={() => notify("Dashboard data is up to date")}>Refresh data <Icon name="clock" size={14} /></button><a className="admin-close-desktop" href="/" aria-label="Back to storefront"><Icon name="close" size={19} /></a></div></header><div className="admin-content">
    {tab === "overview" && <div className="admin-view"><div className="admin-metrics"><div className="admin-metric-card"><span>Revenue · this month</span><strong>KSh 148,420</strong><small className="positive">↑ 18.4% <i>vs last month</i></small></div><div className="admin-metric-card"><span>Orders</span><strong>38</strong><small className="positive">↑ 12.2% <i>this month</i></small></div><div className="admin-metric-card"><span>Pending orders</span><strong>{pendingOrders.toString().padStart(2, "0")}</strong><small className="warning-text">Needs attention today</small></div><div className="admin-metric-card"><span>Repeat customers</span><strong>42%</strong><small className="positive">↑ 6.8% <i>loyalty is growing</i></small></div></div><div className="admin-overview-grid"><div className="admin-panel-card"><div className="admin-card-heading"><div><span>Revenue pulse</span><strong>Weekly order revenue</strong></div><select defaultValue="This week"><option>This week</option><option>Last week</option><option>This month</option></select></div><div className="revenue-chart">{[54, 72, 61, 88, 68, 94, 82].map((height, index) => <div className="revenue-bar" key={index}><span style={{ height: `${height}%` }} /><small>{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][index]}</small></div>)}</div></div><div className="admin-panel-card"><div className="admin-card-heading"><div><span>What people love</span><strong>Top cakes</strong></div><button onClick={() => setTab("cakes")}>View all ↗</button></div>{cakes.slice(0, 4).map((cake, index) => <div className="admin-ranking-row" key={cake.id}><b>0{index + 1}</b><img src={cake.image} alt="" /><span><strong>{cake.name}</strong><small>{cake.category} · {cake.orders} orders</small></span><em>{formatPrice(cake.price)}</em></div>)}</div></div><div className="admin-overview-lower"><div className="admin-panel-card"><div className="admin-card-heading"><div><span>Action queue</span><strong>Pending orders</strong></div><button onClick={() => setTab("orders")}>{pendingOrders} to review ↗</button></div>{orders.filter((item) => item.status === "Pending" || item.status === "Baking").slice(0, 3).map((item) => <div className="admin-order-mini" key={item.id}><span className="status-dot" /><div><strong>{item.id} · {item.customer}</strong><small>{item.cake}</small></div><b>{formatPrice(item.amount)}</b></div>)}</div><div className="admin-panel-card insight-card"><span className="insight-spark"><Icon name="sparkle" size={18} /></span><p className="eyebrow">Today&apos;s insight</p><h3>Saturday is your <em>sweet spot.</em></h3><p>Orders peak between 10am and 1pm. Consider adding one extra delivery run next Saturday.</p><button onClick={() => setTab("analytics")}>Open analytics <Icon name="arrow" size={14} /></button></div></div></div>}
    {tab === "cakes" && <div className="admin-view"><div className="admin-view-heading"><div><p className="eyebrow">Menu control</p><h3>Cake <em>management</em></h3><p>Add, edit, price and publish your menu from here.</p></div><button className="button button-dark" onClick={() => openEditor()}>+ Add a cake</button></div><div className="admin-toolbar"><label className="admin-search"><Icon name="search" size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search cakes..." /></label><span>{filteredCakes.length} menu items</span></div><div className="admin-table"><div className="admin-table-head"><span>Cake</span><span>Price</span><span>Stock</span><span>Margin</span><span>Manage</span></div>{filteredCakes.map((cake) => <div className="admin-table-row" key={cake.id}><div className="admin-cake-cell"><img src={cake.image} alt="" /><span><strong>{cake.name}</strong><small>{cake.category} · {cake.tag}</small></span></div><strong>{formatPrice(cake.price)}</strong><span className={cake.soldOut || cake.stock < 5 ? "low-stock" : "stock-good"}>{cake.soldOut ? "Sold out" : `${cake.stock} ready`}</span><span className="margin-value">{cake.margin}%</span><div className="admin-row-actions"><button onClick={() => openEditor(cake)}>Edit</button><button onClick={() => setCakes((items) => items.map((item) => item.id === cake.id ? { ...item, soldOut: !item.soldOut, stock: item.soldOut ? 12 : 0, tag: !item.soldOut ? "Sold out" : "Available" } : item))}>{cake.soldOut ? "Restock" : "Mark sold out"}</button></div></div>)}</div></div>}
    {tab === "orders" && <div className="admin-view"><div className="admin-view-heading"><div><p className="eyebrow">Every order, in one place</p><h3>Order <em>management</em></h3><p>Accept, update, assign and print without losing the human touch.</p></div><button className="button button-outline" onClick={() => notify("Invoice queue exported")}>Export report <Icon name="arrow" size={14} /></button></div><div className="admin-toolbar"><div className="admin-filter-pills">{["All orders", "Pending", "Baking", "Decorating", "Out for delivery", "Delivered"].map((filter) => <button key={filter} className={orderFilter === filter ? "active" : ""} onClick={() => setOrderFilter(filter)}>{filter}</button>)}</div><span>{filteredOrders.length} orders</span></div><div className="admin-order-list">{filteredOrders.map((item) => <div className="admin-order-card" key={item.id}><div className="order-card-main"><span className={`status-pill status-${item.status.toLowerCase().replaceAll(" ", "-")}`}>{item.status}</span><strong>{item.id}</strong><small>{item.time}</small></div><div><strong>{item.customer}</strong><small>{item.cake}</small></div><div><strong>{formatPrice(item.amount)}</strong><small>{item.delivery} · Home delivery</small></div><label className="admin-inline-select"><span>Status</span><select value={item.status} onChange={(event) => updateOrder(item.id, "status", event.target.value)}><option>Pending</option><option>Accepted</option><option>Baking</option><option>Decorating</option><option>Out for delivery</option><option>Delivered</option><option>Rejected</option></select></label><label className="admin-inline-select"><span>Driver</span><select value={item.driver} onChange={(event) => updateOrder(item.id, "driver", event.target.value)}><option>Unassigned</option><option>David K.</option><option>Faith N.</option><option>Peter M.</option></select></label><div className="admin-order-actions">{item.status === "Pending" && <button onClick={() => updateOrder(item.id, "status", "Accepted")}>Accept</button>}<button onClick={() => notify(`Invoice ${item.id} sent to print queue`)}>Print invoice</button></div></div>)}</div></div>}
    {tab === "delivery" && <div className="admin-view"><div className="admin-view-heading"><div><p className="eyebrow">The last lovely mile</p><h3>Delivery <em>control room</em></h3><p>Assign drivers and keep every handoff visible.</p></div><span className="live-badge"><span /> Live tracking on</span></div><div className="delivery-admin-stats"><div><Icon name="truck" size={18} /><span><strong>12</strong><small>On the road</small></span></div><div><Icon name="clock" size={18} /><span><strong>3</strong><small>Waiting for driver</small></span></div><div><Icon name="check" size={18} /><span><strong>27</strong><small>Delivered this month</small></span></div></div><div className="driver-grid">{[{ name: "David K.", initials: "DK", deliveries: 4, status: "On route", color: "rose" }, { name: "Faith N.", initials: "FN", deliveries: 3, status: "Available", color: "sage" }, { name: "Peter M.", initials: "PM", deliveries: 5, status: "On route", color: "plum" }].map((driver) => <div className="driver-card" key={driver.name}><div className={`driver-avatar ${driver.color}`}>{driver.initials}</div><div><strong>{driver.name}</strong><small>{driver.deliveries} deliveries today</small></div><span className={driver.status === "Available" ? "driver-available" : "driver-route"}>{driver.status}</span></div>)}</div><div className="admin-panel-card"><div className="admin-card-heading"><div><span>Delivery tracking</span><strong>Active routes</strong></div><button onClick={() => notify("Delivery map refreshed")}>Refresh map ↻</button></div><div className="route-list">{orders.filter((item) => item.status === "Out for delivery" || item.status === "Decorating").map((item) => <div key={item.id}><span className="route-pulse" /><div><strong>{item.id} · {item.customer}</strong><small>{item.delivery} · Assigned to {item.driver}</small></div><b>{item.status === "Out for delivery" ? "ETA 32 min" : "Ready in 45 min"}</b></div>)}</div></div></div>}
    {tab === "customers" && <div className="admin-view"><div className="admin-view-heading"><div><p className="eyebrow">People behind the orders</p><h3>Customer <em>care</em></h3><p>See preferences and history without collecting more than you need.</p></div><button className="button button-outline" onClick={() => notify("Customer list exported")}>Export customers <Icon name="arrow" size={14} /></button></div><div className="customer-summary-cards"><div><strong>1,248</strong><span>Total customers</span><small>↑ 8.2% this month</small></div><div><strong>42%</strong><span>Repeat customers</span><small>↑ 6.8% this month</small></div><div><strong>KSh 8,450</strong><span>Average lifetime value</span><small>↑ 12.4% this month</small></div></div><div className="customer-admin-grid"><div className="admin-panel-card"><div className="admin-card-heading"><div><span>Recent customers</span><strong>Customer directory</strong></div><button onClick={() => notify("Directory filters opened")}>Filter ≡</button></div>{[{ name: "Nia Wanjiku", initials: "NW", orders: 8, spend: "KSh 32,400", preference: "Vanilla berry" }, { name: "Maya & Tom", initials: "MT", orders: 4, spend: "KSh 28,700", preference: "Lemon curd" }, { name: "Brian Karanja", initials: "BK", orders: 3, spend: "KSh 14,850", preference: "Dark chocolate" }, { name: "Asha M.", initials: "AM", orders: 2, spend: "KSh 7,200", preference: "Eggless" }].map((person) => <div className="customer-admin-row" key={person.name}><span className="customer-avatar">{person.initials}</span><div><strong>{person.name}</strong><small>{person.orders} orders · likes {person.preference}</small></div><b>{person.spend}</b><button onClick={() => notify(`${person.name}'s order history opened`)}>View</button></div>)}</div><div className="admin-panel-card"><div className="admin-card-heading"><div><span>Privacy-first security</span><strong>Login activity</strong></div><span className="secure-label"><Icon name="check" size={13} /> Safe</span></div><p className="privacy-note">Only operational signals are shown. No message content or sensitive data is stored here.</p>{[{ device: "Chrome on Windows", location: "Approx. Nairobi", time: "Today · 10:42am", failed: "0 failed attempts", suspicious: false }, { device: "Safari on iPhone", location: "Approx. Nairobi", time: "Yesterday · 6:08pm", failed: "1 failed attempt", suspicious: false }, { device: "Chrome on Android", location: "Approx. Mombasa", time: "03 Aug · 2:21am", failed: "3 failed attempts", suspicious: true }].map((login) => <div className={`login-row ${login.suspicious ? "suspicious" : ""}`} key={`${login.device}-${login.time}`}><span className="device-icon"><Icon name="user" size={14} /></span><div><strong>{login.device}</strong><small>{login.location} · {login.time}</small></div><span>{login.suspicious ? "Review alert" : login.failed}</span></div>)}</div></div></div>}
    {tab === "analytics" && <div className="admin-view"><div className="admin-view-heading"><div><p className="eyebrow">Patterns worth noticing</p><h3>Small data, <em>good decisions.</em></h3><p>Turn everyday orders into kinder planning for the studio.</p></div><select className="admin-period-select" defaultValue="Last 30 days"><option>Last 30 days</option><option>Last 90 days</option><option>This year</option></select></div><div className="analytics-highlight-grid"><div><span>Best-selling cake</span><strong>Strawberry Cloud</strong><small>86 orders · 22.4% of menu sales</small></div><div><span>Most profitable flavor</span><strong>Dark chocolate</strong><small>61% gross margin · KSh 18,420</small></div><div><span>Peak order time</span><strong>Saturday · 11am</strong><small>18% of weekly orders arrive here</small></div><div><span>Cart abandonment</span><strong>24.8%</strong><small className="warning-text">↓ 4.1% after adding WhatsApp help</small></div></div><div className="analytics-grid"><div className="admin-panel-card"><div className="admin-card-heading"><div><span>Order volume</span><strong>Orders by day</strong></div><span className="chart-legend"><i /> Orders</span></div><div className="analytics-bars">{[35, 56, 42, 65, 74, 96, 81, 67, 52, 72, 89, 76].map((height, index) => <div key={index}><span style={{ height: `${height}%` }} /><small>{index + 1}</small></div>)}</div></div><div className="admin-panel-card"><div className="admin-card-heading"><div><span>Loyalty signal</span><strong>Repeat customers</strong></div><span className="positive">42%</span></div><div className="donut-chart"><span>42<small>% repeat</small></span></div><div className="repeat-legend"><span><i /> Repeat customers <b>42%</b></span><span><i /> First-time customers <b>58%</b></span></div></div></div></div>}
    {tab === "inventory" && <div className="admin-view"><div className="admin-view-heading"><div><p className="eyebrow">Know what is in the pantry</p><h3>Inventory <em>watch</em></h3><p>Low-stock alerts keep the oven moving and the waste low.</p></div><button className="button button-dark" onClick={() => notify("Purchase order draft created")}>Create purchase order <Icon name="arrow" size={14} /></button></div><div className="inventory-alert"><Icon name="sparkle" size={17} /><span><strong>{stock.filter((item) => item.stock <= item.reorderAt).length} low-stock alerts</strong><small>Restock soon to protect this week&apos;s baking schedule.</small></span><button onClick={() => notify("Low-stock items filtered")}>Review all</button></div><div className="admin-panel-card inventory-card"><div className="admin-table-head inventory-table-head"><span>Ingredient</span><span>In stock</span><span>Reorder point</span><span>Unit cost</span><span>Action</span></div>{stock.map((item) => <div className="inventory-row" key={item.name}><div><strong>{item.name}</strong><small>{item.unit}</small></div><div className="stock-meter"><span><i style={{ width: `${Math.min(100, (item.stock / Math.max(item.reorderAt * 3, 1)) * 100)}%` }} /></span><b className={item.stock <= item.reorderAt ? "low-stock" : "stock-good"}>{item.stock} {item.unit}</b></div><span>{item.reorderAt} {item.unit}</span><span>{item.cost}</span><button onClick={() => { setStock((items) => items.map((entry) => entry.name === item.name ? { ...entry, stock: entry.stock + 10 } : entry)); notify(`${item.name} restocked`); }}>{item.stock <= item.reorderAt ? "Restock now" : "Add stock"}</button></div>)}</div></div>}
    {tab === "reviews" && <div className="admin-view"><div className="admin-view-heading"><div><p className="eyebrow">Keep the room kind</p><h3>Review <em>moderation</em></h3><p>Approve the good words and remove anything that doesn&apos;t belong.</p></div><div className="review-counts"><span><b>{reviews.filter((review) => review.status === "Pending").length}</b> Pending</span><span><b>{reviews.filter((review) => review.status === "Approved").length}</b> Live</span></div></div><div className="review-admin-list">{reviews.map((review) => <div className="review-admin-card" key={review.id}><div className="review-admin-top"><span className="review-avatar">{review.customer.split(" ").map((part) => part[0]).join("")}</span><div><strong>{review.customer}</strong><small>{review.cake} · {review.status}</small></div><span className="admin-review-stars">{Array.from({ length: review.rating }).map((_, index) => <Icon name="star" size={12} key={index} />)}</span></div><blockquote>“{review.quote}”</blockquote><div className="review-admin-actions">{review.status === "Pending" && <button onClick={() => { setReviews((items) => items.map((item) => item.id === review.id ? { ...item, status: "Approved" } : item)); notify("Review approved"); }}>Approve review</button>}<button className="remove-review" onClick={() => { setReviews((items) => items.filter((item) => item.id !== review.id)); notify("Review removed"); }}>Remove</button></div></div>)}</div></div>}
    {tab === "staff" && <div className="admin-view"><div className="admin-view-heading"><div><p className="eyebrow">The right people, the right access</p><h3>Staff & <em>roles</em></h3><p>Give each teammate exactly the access they need to do good work.</p></div><button className="button button-dark" onClick={() => notify("Invite link copied")}>+ Invite staff</button></div><div className="staff-role-layout"><div className="admin-panel-card"><div className="admin-card-heading"><div><span>Team members</span><strong>Studio access</strong></div><span>4 people</span></div>{[{ name: "Billy Kamau", initials: "BK", role: "Super admin", status: "Active" }, { name: "Mary Njeri", initials: "MN", role: "Baker", status: "Active" }, { name: "David Kariuki", initials: "DK", role: "Delivery staff", status: "Active" }, { name: "Faith N.", initials: "FN", role: "Customer support", status: "Invited" }].map((member) => <div className="staff-member" key={member.name}><span className="staff-avatar">{member.initials}</span><div><strong>{member.name}</strong><small>{member.role} · {member.status}</small></div><button onClick={() => setRole(member.role)}>View</button></div>)}</div><div className="admin-panel-card permission-card"><div className="admin-card-heading"><div><span>Permission preview</span><strong>{role}</strong></div><span className="secure-label"><Icon name="check" size={13} /> Scoped</span></div><p>What this role can access in the studio admin.</p><div className="permission-list">{permissions[role].map((permission) => <span key={permission}><Icon name="check" size={14} /> {permission}</span>)}</div><div className="permission-note"><Icon name="lock" size={14} /> Customer privacy controls apply to every role.</div></div></div></div>}
  </div></div>{editor && <div className="admin-editor-backdrop"><form className="admin-editor" onSubmit={saveCake}><button type="button" className="modal-close" onClick={() => setEditor(null)} aria-label="Close cake editor"><Icon name="close" size={19} /></button><p className="eyebrow">{editor ? "Edit menu item" : "New menu item"}</p><h3>{editor ? "Shape this cake." : "Add a new cake."}</h3><label><span>Cake name</span><input required value={newCake.name} onChange={(event) => setNewCake({ ...newCake, name: event.target.value })} placeholder="e.g. Raspberry Rose" /></label><div className="form-row"><label><span>Category</span><select value={newCake.category} onChange={(event) => setNewCake({ ...newCake, category: event.target.value })}><option>Birthday</option><option>Wedding</option><option>Anniversary</option><option>Chocolate</option><option>Vegan / eggless</option><option>Custom</option></select></label><label><span>Starting price</span><input required type="number" min="100" value={newCake.price} onChange={(event) => setNewCake({ ...newCake, price: event.target.value })} /></label></div><label className="admin-upload"><Icon name="upload" size={18} /><span><strong>{newCake.photo || "Upload cake photos"}</strong><small>JPG or PNG · add up to 6 views</small></span><input type="file" accept="image/png,image/jpeg" onChange={(event) => setNewCake({ ...newCake, photo: event.target.files?.[0]?.name ?? "" })} /></label><label className="admin-soldout-toggle"><input type="checkbox" checked={newCake.soldOut} onChange={(event) => setNewCake({ ...newCake, soldOut: event.target.checked })} /><span className="fake-toggle" />Mark as sold out</label><button className="button button-dark full-button" type="submit">{editor ? "Save changes" : "Add cake"} <Icon name="check" size={15} /></button></form></div>}{toast && <div className="toast" role="status"><span><Icon name="check" size={16} /></span>{toast}</div>}</section></main>;
}
